Fix the PCRE macros and make it be statically linked. Also port the Unix changes to windows to that PCRE can be used on any platform.
bk: 4897749euBGmKODjCrNu5bxDS6AitQ

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -873,6 +873,8 @@ Optional Packages:
   --with-encoding         encoding for configuration values (default:
                           iso8859-1)
   --with-pcre             directory containing pcre headers and libraries
+  --with-pcre-include     directory containing pcre headers
+  --with-pcre-lib         directory containing pcre libraries
   --with-tzdata           install timezone data (default: autodetect)
 
 Some influential environment variables:
@@ -7759,7 +7761,6 @@ fi
 	    SHLIB_SUFFIX=".so"
 	    DL_OBJS="tclLoadDl.o"
 	    DL_LIBS=""
-
 	    echo "$as_me:$LINENO: checking for ELF" >&5
 echo $ECHO_N "checking for ELF... $ECHO_C" >&6
 if test "${tcl_cv_ld_elf+set}" = set; then
@@ -13988,6 +13989,21 @@ if test "${with_pcre+set}" = set; then
   withval="$with_pcre"
   with_pcre=${withval}
 fi;
+
+
+# Check whether --with-pcre-include or --without-pcre-include was given.
+if test "${with_pcre_include+set}" = set; then
+  withval="$with_pcre_include"
+  with_pcre_include=${withval}
+fi;
+
+
+# Check whether --with-pcre-lib or --without-pcre-lib was given.
+if test "${with_pcre_lib+set}" = set; then
+  withval="$with_pcre_lib"
+  with_pcre_lib=${withval}
+fi;
+
     echo "$as_me:$LINENO: checking for PCRE configuration" >&5
 echo $ECHO_N "checking for PCRE configuration... $ECHO_C" >&6
 
@@ -13995,6 +14011,7 @@ echo $ECHO_N "checking for PCRE configuration... $ECHO_C" >&6
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
+	    PCRE_CONFIG="pcre-config"
 	    # First check to see if --with-pcre was specified.
 	    if test x"${with_pcre}" != x ; then
 		if test -f "${with_pcre}/include/pcre.h" -a \
@@ -14003,6 +14020,7 @@ else
 		    ac_cv_c_pcre=`(cd ${with_pcre}; pwd)`
 		    PCRE_INCLUDE="-I${ac_cv_c_pcre}/include"
 		    PCRE_LIBS="-L${ac_cv_c_pcre}/lib -lpcre"
+		    PCRE_CONFIG="${ac_cv_c_pcre}/bin/pcre-config"
 		else
 		    { { echo "$as_me:$LINENO: error: ${with_pcre} directory doesn't contain pcre header and/or library" >&5
 echo "$as_me: error: ${with_pcre} directory doesn't contain pcre header and/or library" >&2;}
@@ -14010,44 +14028,66 @@ echo "$as_me: error: ${with_pcre} directory doesn't contain pcre header and/or l
 		fi
 	    fi
 
-	    if test x"${ac_cv_c_pcre}" = x ; then
-		# Try pcre-config if it exists
-		ac_cv_c_pcre=`pcre-config --prefix 2>/dev/null`
-		if test "$?" -eq 0; then
-		    PCRE_INCLUDE=`pcre-config --cflags 2>/dev/null`
-		    PCRE_LIBS=`pcre-config --libs 2>/dev/null`
+	    if test x"${with_pcre_include}" != x ; then
+	        if test -f "${with_pcre_include}/pcre.h" ; then
+	       	    PCRE_INCLUDE="-I${with_pcre_include}"
+		else
+	            { { echo "$as_me:$LINENO: error: ${with_pcre_include} directory doesn't contain pcre.h" >&5
+echo "$as_me: error: ${with_pcre_include} directory doesn't contain pcre.h" >&2;}
+   { (exit 1); exit 1; }; }
+	        fi
+	    fi
+
+	    if test x"${with_pcre_lib}" != x ; then
+	        if test -f "${with_pcre_lib}/libpcre.a" ; then
+		    PCRE_LIBS="-L${with_pcre_lib} -lpcre"
+		else
+		    { { echo "$as_me:$LINENO: error: ${with_pcre_lib} directory doesn't contain libpcre.a" >&5
+echo "$as_me: error: ${with_pcre_lib} directory doesn't contain libpcre.a" >&2;}
+   { (exit 1); exit 1; }; }
 		fi
 	    fi
 
-	    # check in a few common install locations
-	    if test x"${ac_cv_c_pcre}" = x ; then
-		for i in \
-			`ls -d ${exec_prefix} 2>/dev/null` \
-			`ls -d ${prefix} 2>/dev/null` \
-			`ls -d /usr/local 2>/dev/null` \
-			`ls -d /usr/contrib 2>/dev/null` \
-			`ls -d /usr 2>/dev/null` \
-			; do
-		    if test -f "${i}/include/pcre.h" -a \
-			\( -f "${i}/lib/libpcre.so" -o \
-			   -f "${i}/lib/libpcre.a" \); then
-			ac_cv_c_pcre=`(cd $i; pwd)`
-			PCRE_INCLUDE="-I${ac_cv_c_pcre}/include"
-			PCRE_LIBS="-L${ac_cv_c_pcre}/lib -lpcre"
-			break
-		    fi
-		done
+	    if test x"${PCRE_INCLUDE}" = x -o x"${PCRE_LIBS}" = x ; then
+	        if test x"${ac_cv_c_pcre}" = x ; then
+	        	# Try pcre-config if it exists
+	        	ac_cv_c_pcre=`${PCRE_CONFIG} --prefix 2>/dev/null`
+	        	if test "$?" -eq 0; then
+	        	    PCRE_INCLUDE=`${PCRE_CONFIG} --cflags 2>/dev/null`
+	        	    PCRE_LIBS=`${PCRE_CONFIG} --libs 2>/dev/null`
+	        	fi
+	        fi
+
+	        # check in a few common install locations
+	        if test x"${ac_cv_c_pcre}" = x ; then
+	        	for i in \
+	        		`ls -d ${exec_prefix} 2>/dev/null` \
+	        		`ls -d ${prefix} 2>/dev/null` \
+	        		`ls -d /usr/local 2>/dev/null` \
+	        		`ls -d /usr/contrib 2>/dev/null` \
+	        		`ls -d /usr 2>/dev/null` \
+	        		; do
+	        	    if test -f "${i}/include/pcre.h" -a \
+	        		\( -f "${i}/lib/libpcre.so" -o \
+	        		   -f "${i}/lib/libpcre.a" \); then
+	        		ac_cv_c_pcre=`(cd $i; pwd)`
+	        		PCRE_INCLUDE="-I${ac_cv_c_pcre}/include"
+	        		PCRE_LIBS="-L${ac_cv_c_pcre}/lib -lpcre"
+	        		break
+	        	    fi
+	        	done
+	        fi
 	    fi
 
 fi
 
 
-    if test x"${ac_cv_c_pcre}" = x ; then
+    if test x"${PCRE_INCLUDE}" = x -o x"${PCRE_LIBS}" = x ; then
 	{ echo "$as_me:$LINENO: WARNING: Can't find PCRE configuration, PCRE won't be used" >&5
 echo "$as_me: WARNING: Can't find PCRE configuration, PCRE won't be used" >&2;}
     else
-	echo "$as_me:$LINENO: result: found PCRE configuration at ${ac_cv_c_pcre}" >&5
-echo "${ECHO_T}found PCRE configuration at ${ac_cv_c_pcre}" >&6
+	echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
     fi
 
 
@@ -14071,7 +14111,7 @@ fi;
 	enable_pcre=yes
     fi
 
-    if test x"${ac_cv_c_pcre}" = x ; then
+    if test x"${ac_cv_c_pcre}" = x -a x"${PCRE_INCLUDE}" = x -a x"${PCRE_LIBS}" = x ; then
 	echo "$as_me:$LINENO: result: pcre configuration not found" >&5
 echo "${ECHO_T}pcre configuration not found" >&6
     else
diff --git a/win/configure b/win/configure
--- a/win/configure
+++ b/win/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="../generic/tcl.h"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS BK_DIR BK_HDRS BK_SRCS BK_OBJS BK_INCLUDES BK_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP AR RANLIB RC SET_MAKE TCL_THREADS CYGPATH CELIB_DIR DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING CFLAGS_DEFAULT LDFLAGS_DEFAULT TCL_VERSION TCL_MAJOR_VERSION TCL_MINOR_VERSION TCL_PATCH_LEVEL TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_STUB_LIB_PATH TCL_INCLUDE_SPEC TCL_BUILD_STUB_LIB_SPEC TCL_BUILD_STUB_LIB_PATH TCL_DLL_FILE TCL_SRC_DIR TCL_BIN_DIR TCL_DBGX CFG_TCL_SHARED_LIB_SUFFIX CFG_TCL_UNSHARED_LIB_SUFFIX CFG_TCL_EXPORT_FILE_SUFFIX EXTRA_CFLAGS DEPARG CC_OBJNAME CC_EXENAME LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LDFLAGS_CONSOLE LDFLAGS_WINDOW STLIB_LD SHLIB_LD SHLIB_LD_LIBS SHLIB_CFLAGS SHLIB_SUFFIX TCL_SHARED_BUILD LIBS_GUI DLLSUFFIX LIBPREFIX LIBSUFFIX EXESUFFIX LIBRARIES MAKE_LIB POST_MAKE_LIB MAKE_DLL MAKE_EXE TCL_BUILD_LIB_SPEC TCL_LD_SEARCH_FLAGS TCL_NEEDS_EXP_FILE TCL_BUILD_EXP_FILE TCL_EXP_FILE TCL_LIB_VERSIONS_OK TCL_PACKAGE_PATH TCL_DDE_VERSION TCL_DDE_MAJOR_VERSION TCL_DDE_MINOR_VERSION TCL_DDE_PATCH_LEVEL TCL_REG_VERSION TCL_REG_MAJOR_VERSION TCL_REG_MINOR_VERSION TCL_REG_PATCH_LEVEL RC_OUT RC_TYPE RC_INCLUDE RC_DEFINE RC_DEFINES RES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS BK_DIR BK_HDRS BK_SRCS BK_OBJS BK_INCLUDES BK_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP AR RANLIB RC SET_MAKE TCL_THREADS CYGPATH CELIB_DIR DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING PCRE_INCLUDE PCRE_LIBS CFLAGS_DEFAULT LDFLAGS_DEFAULT TCL_VERSION TCL_MAJOR_VERSION TCL_MINOR_VERSION TCL_PATCH_LEVEL TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_STUB_LIB_PATH TCL_INCLUDE_SPEC TCL_BUILD_STUB_LIB_SPEC TCL_BUILD_STUB_LIB_PATH TCL_DLL_FILE TCL_SRC_DIR TCL_BIN_DIR TCL_DBGX CFG_TCL_SHARED_LIB_SUFFIX CFG_TCL_UNSHARED_LIB_SUFFIX CFG_TCL_EXPORT_FILE_SUFFIX EXTRA_CFLAGS DEPARG CC_OBJNAME CC_EXENAME LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LDFLAGS_CONSOLE LDFLAGS_WINDOW STLIB_LD SHLIB_LD SHLIB_LD_LIBS SHLIB_CFLAGS SHLIB_SUFFIX TCL_SHARED_BUILD LIBS_GUI DLLSUFFIX LIBPREFIX LIBSUFFIX EXESUFFIX LIBRARIES MAKE_LIB POST_MAKE_LIB MAKE_DLL MAKE_EXE TCL_BUILD_LIB_SPEC TCL_LD_SEARCH_FLAGS TCL_NEEDS_EXP_FILE TCL_BUILD_EXP_FILE TCL_EXP_FILE TCL_LIB_VERSIONS_OK TCL_PACKAGE_PATH TCL_DDE_VERSION TCL_DDE_MAJOR_VERSION TCL_DDE_MINOR_VERSION TCL_DDE_PATCH_LEVEL TCL_REG_VERSION TCL_REG_MAJOR_VERSION TCL_REG_MINOR_VERSION TCL_REG_PATCH_LEVEL RC_OUT RC_TYPE RC_INCLUDE RC_DEFINE RC_DEFINES RES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -808,6 +808,7 @@ Optional Features:
   --enable-shared         build and link with shared libraries --enable-shared
   --enable-64bit          enable 64bit support (where applicable)
   --enable-wince          enable Win/CE support (where applicable)
+  --enable-pcre           whether to enable pcre (default: off)
   --enable-symbols        build with debugging symbols --disable-symbols
 
 Optional Packages:
@@ -816,6 +817,9 @@ Optional Packages:
   --with-bk              directory containing BK source
   --with-encoding              encoding for configuration values
   --with-celib=DIR        use Windows/CE support library from DIR
+  --with-pcre             directory containing pcre headers and libraries
+  --with-pcre-include     directory containing pcre headers
+  --with-pcre-lib         directory containing pcre libraries
 
 Some influential environment variables:
   CC          C compiler command
@@ -4260,6 +4264,183 @@ _ACEOF
 
 
 
+#------------------------------------------------------------------------------
+#       Check if we want to use pcre
+#------------------------------------------------------------------------------
+
+
+
+# Check whether --with-pcre or --without-pcre was given.
+if test "${with_pcre+set}" = set; then
+  withval="$with_pcre"
+  with_pcre=${withval}
+fi;
+
+
+# Check whether --with-pcre-include or --without-pcre-include was given.
+if test "${with_pcre_include+set}" = set; then
+  withval="$with_pcre_include"
+  with_pcre_include=${withval}
+fi;
+
+
+# Check whether --with-pcre-lib or --without-pcre-lib was given.
+if test "${with_pcre_lib+set}" = set; then
+  withval="$with_pcre_lib"
+  with_pcre_lib=${withval}
+fi;
+
+    echo "$as_me:$LINENO: checking for PCRE configuration" >&5
+echo $ECHO_N "checking for PCRE configuration... $ECHO_C" >&6
+
+    if test "${ac_cv_c_pcre+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	    PCRE_CONFIG="pcre-config"
+	    # First check to see if --with-pcre was specified.
+	    if test x"${with_pcre}" != x ; then
+		if test -f "${with_pcre}/include/pcre.h" -a \
+			\( -f "${with_pcre}/lib/libpcre.so" -o \
+			  -f "${with_pcre}/lib/libpcre.a" \); then
+		    ac_cv_c_pcre=`(cd ${with_pcre}; pwd)`
+		    PCRE_INCLUDE="-I${ac_cv_c_pcre}/include"
+		    PCRE_LIBS="-L${ac_cv_c_pcre}/lib -lpcre"
+		    PCRE_CONFIG="${ac_cv_c_pcre}/bin/pcre-config"
+		else
+		    { { echo "$as_me:$LINENO: error: ${with_pcre} directory doesn't contain pcre header and/or library" >&5
+echo "$as_me: error: ${with_pcre} directory doesn't contain pcre header and/or library" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+	    fi
+
+	    if test x"${with_pcre_include}" != x ; then
+	        if test -f "${with_pcre_include}/pcre.h" ; then
+	       	    PCRE_INCLUDE="-I${with_pcre_include}"
+		else
+	            { { echo "$as_me:$LINENO: error: ${with_pcre_include} directory doesn't contain pcre.h" >&5
+echo "$as_me: error: ${with_pcre_include} directory doesn't contain pcre.h" >&2;}
+   { (exit 1); exit 1; }; }
+	        fi
+	    fi
+
+	    if test x"${with_pcre_lib}" != x ; then
+	        if test -f "${with_pcre_lib}/libpcre.a" ; then
+		    PCRE_LIBS="-L${with_pcre_lib} -lpcre"
+		else
+		    { { echo "$as_me:$LINENO: error: ${with_pcre_lib} directory doesn't contain libpcre.a" >&5
+echo "$as_me: error: ${with_pcre_lib} directory doesn't contain libpcre.a" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+	    fi
+
+	    if test x"${PCRE_INCLUDE}" = x -o x"${PCRE_LIBS}" = x ; then
+	        if test x"${ac_cv_c_pcre}" = x ; then
+	        	# Try pcre-config if it exists
+	        	ac_cv_c_pcre=`${PCRE_CONFIG} --prefix 2>/dev/null`
+	        	if test "$?" -eq 0; then
+	        	    PCRE_INCLUDE=`${PCRE_CONFIG} --cflags 2>/dev/null`
+	        	    PCRE_LIBS=`${PCRE_CONFIG} --libs 2>/dev/null`
+	        	fi
+	        fi
+
+	        # check in a few common install locations
+	        if test x"${ac_cv_c_pcre}" = x ; then
+	        	for i in \
+	        		`ls -d ${exec_prefix} 2>/dev/null` \
+	        		`ls -d ${prefix} 2>/dev/null` \
+	        		`ls -d /usr/local 2>/dev/null` \
+	        		`ls -d /usr/contrib 2>/dev/null` \
+	        		`ls -d /usr 2>/dev/null` \
+	        		; do
+	        	    if test -f "${i}/include/pcre.h" -a \
+	        		\( -f "${i}/lib/libpcre.so" -o \
+	        		   -f "${i}/lib/libpcre.a" \); then
+	        		ac_cv_c_pcre=`(cd $i; pwd)`
+	        		PCRE_INCLUDE="-I${ac_cv_c_pcre}/include"
+	        		PCRE_LIBS="-L${ac_cv_c_pcre}/lib -lpcre"
+	        		break
+	        	    fi
+	        	done
+	        fi
+	    fi
+
+fi
+
+
+    if test x"${PCRE_INCLUDE}" = x -o x"${PCRE_LIBS}" = x ; then
+	{ echo "$as_me:$LINENO: WARNING: Can't find PCRE configuration, PCRE won't be used" >&5
+echo "$as_me: WARNING: Can't find PCRE configuration, PCRE won't be used" >&2;}
+    else
+	echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
+    fi
+
+
+
+
+
+    echo "$as_me:$LINENO: checking whether to enable pcre in Tcl" >&5
+echo $ECHO_N "checking whether to enable pcre in Tcl... $ECHO_C" >&6
+    # Check whether --enable-pcre or --disable-pcre was given.
+if test "${enable_pcre+set}" = set; then
+  enableval="$enable_pcre"
+  enable_pcre=$enableval
+else
+  enable_pcre=no
+fi;
+
+    if test "${enable_pcre+set}" = set; then
+	enableval="$enable_pcre"
+	enable_pcre=$enableval
+    else
+	enable_pcre=yes
+    fi
+
+    if test x"${ac_cv_c_pcre}" = x -a x"${PCRE_INCLUDE}" = x -a x"${PCRE_LIBS}" = x ; then
+	echo "$as_me:$LINENO: result: pcre configuration not found" >&5
+echo "${ECHO_T}pcre configuration not found" >&6
+    else
+	if test "$enable_pcre" = "default" ; then
+	    echo "$as_me:$LINENO: result: pcre default" >&5
+echo "${ECHO_T}pcre default" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_DEFAULT_PCRE 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PCRE 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define PCRE_STATIC 1
+_ACEOF
+
+	elif test "$enable_pcre" = "yes" ; then
+	    echo "$as_me:$LINENO: result: pcre enabled" >&5
+echo "${ECHO_T}pcre enabled" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PCRE 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define PCRE_STATIC 1
+_ACEOF
+
+	else
+	    PCRE_INCLUDE=
+	    PCRE_LIBS=
+	    echo "$as_me:$LINENO: result: no pcre" >&5
+echo "${ECHO_T}no pcre" >&6
+	fi
+    fi
+
+
 #--------------------------------------------------------------------
 # Set the default compiler switches based on the --enable-symbols
 # option.  This macro depends on C flags, and should be called
@@ -5163,6 +5344,8 @@ s,@DL_LIBS@,$DL_LIBS,;t t
 s,@CFLAGS_DEBUG@,$CFLAGS_DEBUG,;t t
 s,@CFLAGS_OPTIMIZE@,$CFLAGS_OPTIMIZE,;t t
 s,@CFLAGS_WARNING@,$CFLAGS_WARNING,;t t
+s,@PCRE_INCLUDE@,$PCRE_INCLUDE,;t t
+s,@PCRE_LIBS@,$PCRE_LIBS,;t t
 s,@CFLAGS_DEFAULT@,$CFLAGS_DEFAULT,;t t
 s,@LDFLAGS_DEFAULT@,$LDFLAGS_DEFAULT,;t t
 s,@TCL_VERSION@,$TCL_VERSION,;t t
